using CanfarDesktop.Models;
using CanfarDesktop.Models.Notebook;

namespace CanfarDesktop.Helpers.Notebook;

/// <summary>
/// Builds a ready-to-run analysis notebook (nbformat doc) for a downloaded observation: a metadata
/// header, an astropy load cell (file path + WCS), and a template stub (image quick-look / aperture
/// photometry / cube moments). Pure + serialisable via <see cref="NotebookParser"/>, so the hand-off
/// from a results row → a pre-filled cell (SCI-10) is unit-testable. The kernel must have astropy
/// (and photutils/spectral-cube for the template) — the header cell says so.
/// </summary>
public static class AnalysisNotebookBuilder
{
    /// <summary>Templates the agent/user can request.</summary>
    public static readonly string[] Templates = { "image", "photometry", "cube" };

    public static NotebookDocument Build(DownloadedObservation obs, string? template)
    {
        var t = (template ?? "").Trim().ToLowerInvariant();
        if (t is "" or "auto") t = "image";

        var path = (obs.LocalPath ?? string.Empty).Replace('\\', '/');
        var title = !string.IsNullOrEmpty(obs.TargetName) ? obs.TargetName
                  : !string.IsNullOrEmpty(obs.ObservationID) ? obs.ObservationID
                  : obs.PublisherID;

        var cells = new List<NotebookCell>
        {
            Markdown(HeaderMarkdown(obs, title, t)),
            Code(LoadCode(path)),
            Code(t switch
            {
                "cube" => CubeStub(),
                "photometry" => PhotometryStub(),
                _ => ImageStub(),
            }),
        };

        return new NotebookDocument
        {
            Cells = cells,
            Metadata = new NotebookMetadata { KernelSpec = new KernelSpec(), LanguageInfo = new LanguageInfo() },
        };
    }

    private static NotebookCell Markdown(string text) => new() { CellType = "markdown", SourceText = text };

    private static NotebookCell Code(string text) =>
        new() { CellType = "code", SourceText = text, Outputs = new List<CellOutput>(), ExecutionCount = null };

    private static string HeaderMarkdown(DownloadedObservation obs, string title, string template) =>
$@"# Analysis — {title}

| Field | Value |
|---|---|
| Publisher ID | `{obs.PublisherID}` |
| Collection | {obs.Collection} |
| Instrument | {obs.Instrument} |
| Cal. level | {obs.CalLevel} |
| Local file | `{obs.LocalPath}` |

Auto-generated by Verbinal (`create_analysis_notebook`, template **{template}**). The cells below load the
FITS with astropy (WCS ready). **Requires `astropy`** in the kernel (and `photutils` / `spectral-cube` for
the template) — `pip install astropy photutils spectral-cube` if missing.";

    private static string LoadCode(string path) =>
$@"import numpy as np
from astropy.io import fits
from astropy.wcs import WCS

path = r'{path}'
hdul = fits.open(path)
hdul.info()

# First HDU that carries data (CADC products often have an empty primary HDU)
hdu = hdul[0] if hdul[0].data is not None else next((h for h in hdul if h.data is not None), hdul[0])
header, data = hdu.header, hdu.data
wcs = WCS(header)
print('shape:', None if data is None else data.shape, '| BUNIT:', header.get('BUNIT'))";

    private static string ImageStub() =>
@"# Quick look (zscale + WCS axes)
import matplotlib.pyplot as plt
from astropy.visualization import ZScaleInterval, ImageNormalize

if data is not None and data.ndim == 2:
    norm = ImageNormalize(data, interval=ZScaleInterval())
    ax = plt.subplot(projection=wcs)
    im = ax.imshow(data, origin='lower', norm=norm, cmap='gray')
    plt.colorbar(im, label=header.get('BUNIT', ''))
    ax.grid(color='white', ls=':', alpha=0.5)
    plt.show()";

    private static string PhotometryStub() =>
@"# Aperture photometry — set the source position + radius, then run
from astropy.coordinates import SkyCoord
import astropy.units as u
from photutils.aperture import SkyCircularAperture, aperture_photometry

# TODO: your source position (degrees)
coord = SkyCoord(ra=0.0, dec=0.0, unit='deg')
aperture = SkyCircularAperture(coord, r=2.0 * u.arcsec).to_pixel(wcs)
print(aperture_photometry(data, aperture))
print('Pixel units (BUNIT):', header.get('BUNIT'))";

    private static string CubeStub() =>
@"# Spectral cube — moment map + spectrum (edit the spaxel)
from spectral_cube import SpectralCube

cube = SpectralCube.read(path)  # carries SPECSYS / RESTFRQ / beam
print(cube)

mom0 = cube.moment(order=0)     # integrated intensity (moment 0)
mom0.quicklook()

# Spectrum at the central spaxel — edit (x, y)
x, y = cube.shape[2] // 2, cube.shape[1] // 2
cube[:, y, x].quicklook()";
}
